### ISSUE TITLE
Incorrect hashes when dumping

### ISSUE THREAD

**Issue by tofie** [EmK530/BloxDump#7]
the filename seems to be randomly generated when dumped. is there a way to disable this behaviour, and instead convert the hashes from the files in the cache folder into the filenames of the dumped files?

**Comment by EmK530** [comment]
The filename uses the hash from the asset's download link
Due to the method being used to dump assets without messing with the client, I can't actually know the asset IDs being downloaded so I can't get their true name, really sorry about that.
Someday though I could probably make another bloxdump variant to fix this
